service: sqs-lambda-tutorial

custom:
  queueName: TutorialSQS.fifo

provider:
  name: aws
  runtime: python3.8
  stage: production
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource:
        Fn::GetAtt: [ SQSQueue, Arn ]

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - venv/**

functions:
  start-lambda:
    handler: handler.start
    events:
      - schedule: rate(2 minutes)
    environment:
      SQS_URL:
        Ref: SQSQueue
  end-lambda:
    handler: handler.end
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ SQSQueue, Arn ]

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueName}
        ContentBasedDeduplication: true
        FifoQueue: true